insert into tb_creditcard_transaction (
          transaction_id
        , credit_card_id
        , credit_card_status
        , gateway_order_reference
        , gateway_payment_reference
        , acquirer
        , tid
        , nsu
        , authorization_nsu
        , capture_nsu
        , cancel_nsu
        , number_of_installments
        , installment_type
        , authorization_code
        , authorization_tid
        , capture_tid
        , cancel_tid
        , holder_name
        , masked_number
        , brand
        , expiration_month
        , expiration_year
        , currency
        , authorization_date
        , capture_date
        , cancel_date
        , refund_date
        , gateway_cancellation_reference
        , gateway_response_message
        , gateway_response_code
        , created_at
        , updated_at
) values (
          :transaction_id
        , :credit_card_id
        , :credit_card_status
        , :gateway_order_reference
        , :gateway_payment_reference
        , :acquirer
        , :tid
        , :nsu
        , :authorization_nsu
        , :capture_nsu
        , :cancel_nsu
        , :number_of_installments
        , :installment_type
        , :authorization_code
        , :authorization_tid
        , :capture_tid
        , :cancel_tid
        , :holder_name
        , :masked_number
        , :brand
        , :expiration_month
        , :expiration_year
        , :currency
        , :authorization_date
        , :capture_date
        , :cancel_date
        , :refund_date
        , :gateway_cancellation_reference
        , :gateway_response_message
        , :gateway_response_code
        , :created_at
        , :updated_at
)