filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
  - paths:
      - /var/log/wallet/wallet-app.log
    type: log
    encoding: utf-8
    enabled: true

    json.keys_under_root: true
    json.overwrite_keys: true
    json.ignore_decoding_error: true

output.elasticsearch:
  #HML
  #hosts: ["https://search-ame-hml-es-logs-hqewyihkbx6lcnvaju4e4amqtq.us-east-1.es.amazonaws.com:443"]
  #index: "ame-hml-tsk-walletv2-%{+yyyy.MM.dd}"

  #PROD
  hosts: ["https://search-ame-prd-es-logs-g3lhxxcweruuz5zggwishxxwfy.us-east-1.es.amazonaws.com:443"]
  index: "ame-prd-tsk-walletv2-%{+yyyy.MM.dd}"

setup.template.name: "walletv2"
setup.template.fields: "template.yml"
setup.template.overwrite: true
setup.template.pattern: "walletv2-*"
setup.template.enabled: true
